# Generated by Django 5.1.3 on 2024-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("categoria", models.CharField(max_length=50)),
            ],
            options={"db_table": "categoria", "managed": False,},
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                ("id_plato", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={"db_table": "plato", "managed": False,},
        ),
    ]
